### ISSUE TITLE
Customer has custom ADFS - cannot authenticate

### ISSUE THREAD

**Issue by arpIdeas** [scottdurow/dataverse-auth#44]
I'm trying to levarage `dataverse-gen` and `dataverse-auth` for some Dynamics 365 webscripting, but I'm having trouble creating a sign-in token.

Specifically, running the `dataverse-auth` command and progressing through the login screen leaves me with the following:

```
Error
Error: Get Token request returned http error: 400 and server response: {"error":"interaction_required","error_description":"AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '00000007-0000-0000-c000-000000000000'. Trace ID: c6a6f73b-b61d-4645-bd53-e018d4264101 Correlation ID: 4287cf00-5217-4609-82d7-babc294ad79e Timestamp: 2024-03-07 16:17:24Z","error_codes":[50076],"timestamp":"2024-03-07 16:17:24Z","trace_id":"c6a6f73b-b61d-4645-bd53-e018d4264101","correlation_id":"4287cf00-5217-4609-82d7-babc294ad79e","error_uri":"https://login.windows.net/error?code=50076","suberror":"basic_action"}
    at Logger.createError (\node_modules\adal-node\lib\log.js:216:13)
    at \node_modules\adal-node\lib\oauth2client.js:502:26
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Token Aquisition failed:{}
ERROR:Error: Get Token request returned http error: 400 and server response: {"error":"interaction_required","error_description":"AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '00000007-0000-0000-c000-000000000000'. Trace ID: c6a6f73b-b61d-4645-bd53-e018d4264101 Correlation ID: 4287cf00-5217-4609-82d7-babc294ad79e Timestamp: 2024-03-07 16:17:24Z","error_codes":[50076],"timestamp":"2024-03-07 16:17:24Z","trace_id":"c6a6f73b-b61d-4645-bd53-e018d4264101","correlation_id":"4287cf00-5217-4609-82d7-babc294ad79e","error_uri":"https://login.windows.net/error?code=50076","suberror":"basic_action"}
```

The browser that appears for the sign-in process fails to display the final 2FA screen and is effectively "frozen", with the above error shown in the console.

Attempting a device-based sign-in also failed.

Any suggestions on what might be the problem?

Note that tools such as XrmToolbox are capable of signing in without problems.

**Comment by smanessis** [comment]
Hey @arpIdeas, I'm having the same issue. Have you found any workaround?

**Comment by beyro** [comment]
Same exact issue for me. At the point I would usually get the MFA prompt, the interactive control freezes and I get the error in the terminal.  We're looking to adopt Dataverse-ify but that's not going to happen if we can't authenticate. I am able to authenticate fine using the PAC CLI, XRM Toolbox, etc.

**Comment by beyro** [comment]
@smanessis and @arpIdeas - I just found a workaround if you use the Authenticator app.

In the login prompt, I clicked on "Other ways to sign in" and then selected "send a code to the Authenticator app" and this worked for me :)
